name: Build and Push to ECR

on:
  push:
    branches:
      - master

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: 662792376110.dkr.ecr.us-east-1.amazonaws.com
  ECR_REPOSITORY: demo

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Java app with Gradle
        run: |
          npm install
          ls -lat

      # ✅ Generate dynamic tags and export them to the environment
      - name: Generate Docker image tag and URI
        id: vars
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          TIMESTAMP=$(date '+%Y%m%d%H%M%S')
          #IMAGE_TAG="${SHORT_SHA}-${TIMESTAMP}"
          #IMAGE_URI="${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${IMAGE_TAG"
          IMAGE_URI="${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:20-10"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV
          echo "✅ Generated image: $IMAGE_URI"

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_URI .
          docker images

      - name: Push Docker image to Amazon ECR
        run: docker push $IMAGE_URI
